### ISSUE TITLE
[Question] Is it possible to change the range of the results `published_data_search` ?

### ISSUE THREAD

**Issue by eunbee31** [gsong/python-epo-ops-client#43]
First of all, great work you've done! Thanks a lot!

This is what I found in [EPO FAQ](https://www.epo.org/service-support/faq/searching-patents/ops_fr.html):
> By default, OPS displays only the first 25 results but if you want to see more, you can change the interval at the end of the URL ("&Range=xx-xx"). You will then be able to download batches of up to 100 results at a time:
> 
> "&Range=1-100"
> 
> However, OPS can only display a total of 2,000 results. If your list of results exceeds this number, you will need to limit your query to reduce the number of search results.

Also, I saw [here](https://github.com/gsong/python-epo-ops-client/blob/e589eff5cbdb621ce37ab090c115983326477714/epo_ops/api.py#L89) that you explicitly put the range. Is it possible to change the range from 1 to 1000 as it's said in the FAQ?

Thank you.

**Comment by gsong** [comment]
@eunbee31 `range_begin=1` and `range_end=25` are defaults, so you can override them when calling `published_data_search()` method, e.g. `published_data_search(cql, range_end=100)`.

Can you give that a shot?

**Comment by eunbee31** [comment]
Hi @gsong! Yes I already tried it but it didn't work. Now I'm not sure why it failed. I will try it again and keep you inform.
Thank you for your reply.
