### ISSUE TITLE
404 HTTP Error in Search

### ISSUE THREAD

**Issue by brendasalenave** [gsong/python-epo-ops-client#54]
I am trying to use the python-epo-ops-client library to perform a search; however, for some searches (not all), I am getting a 404 response status.

Here is a minimal example of a situation where this error occurs:

```
import epo_ops

key = '****'
consumer_secret = '*******'

client = epo_ops.Client(key=key, secret=consumer_secret)  # Instantiate client

query = '(txt all "water" AND "derailleur" AND "reuse") AND (cl all "E03B")'

response = client.published_data_search(
    cql=query, 
    range_begin=1,
    range_end=100
)
```

I am using `Python 3.9` and `python_epo_ops_client` version `4.0.0`.

Does anyone know how to fix this or indicate what I am doing wrong?

**Comment by gsong** [comment]
@brendasalenave You can try the API directly at <https://developers.epo.org/ops-v3-2/apis/get/published-data/search> to verify that your query works. I get the same `404` result when I test it there, so you must reformulate your query.
